CREATE TABLE `logs` (
	`ID` INT(10) NOT NULL AUTO_INCREMENT,
	`Timestamp` TIMESTAMP NULL DEFAULT current_timestamp(),
	`EventID` SMALLINT(5) NULL DEFAULT NULL,
	`Player` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	`Event` TEXT NULL DEFAULT NULL COLLATE 'utf8mb4_bin',
	PRIMARY KEY (`ID`) USING BTREE,
	INDEX `ID` (`ID`) USING BTREE
)
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
;